In [9]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(len(arr))
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.std())
print(arr.mean())

6
60
10
210
17.07825127659933
35.0


In [4]:
import numpy as np
print("setup successful")

setup successful


In [16]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[0])
print(arr [-1])
print(arr[4:6])

10
60
[50 60]


In [17]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
reshaped=arr.reshape(2,3)
print(reshaped)

[[10 20 30]
 [40 50 60]]


In [18]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr+10)

[20 30 40 50]


In [22]:
random_arr=np.random.radint(1,50,size=5)
print(random_arr)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [27]:
random_arr=np.random.randint(1,40, size=3)
print(random_arr)

[22  1 12]


In [29]:
random_arr=np.random.randint(1,100, size=5)
print(random_arr)

[65 41 74 98 10]


In [30]:
a=np.random.randint(1,10,size=1)
print(a)

[3]


In [31]:
num=[3,5,7,10,12]
print(num[0])
print(len(num))
print(min(num))
print(max(num))
print(sum(num))
num.append(5)
print (num)

3
5
3
12
37
[3, 5, 7, 10, 12, 5]


In [34]:
num=[3,5,7,8]
num.append(15)
print(num)


[3, 5, 7, 8, 15]
