In [9]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(len(arr))
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.std())
print(arr.mean())

6
60
10
210
17.07825127659933
35.0


In [4]:
import numpy as np
print("setup successful")

setup successful


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)
print(a*b)



[ 7  9 11 13 15]
[ 6 14 24 36 50]


In [16]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[0])
print(arr [-1])
print(arr[4:6])

10
60
[50 60]


In [6]:
import numpy as np
a=np.array([3,5,7,9])
b=np.array([2,3,4,5])
r=np.dot(a,b)
print(r)

94


In [17]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
reshaped=arr.reshape(2,3)
print(reshaped)

[[10 20 30]
 [40 50 60]]


In [8]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a @ b


array([[19, 22],
       [43, 50]])

In [18]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr+10)

[20 30 40 50]


In [9]:
x=np.array([[3,4],[3,7]])
y=np.array([[4,6],[7,9]])
np.matmul(x,y)


array([[40, 54],
       [61, 81]])

In [22]:
random_arr=np.random.radint(1,50,size=5)
print(random_arr)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [27]:
random_arr=np.random.randint(1,40, size=3)
print(random_arr)

[22  1 12]


In [29]:
random_arr=np.random.randint(1,100, size=5)
print(random_arr)

[65 41 74 98 10]


In [30]:
a=np.random.randint(1,10,size=1)
print(a)

[3]


In [31]:
num=[3,5,7,10,12]
print(num[0])
print(len(num))
print(min(num))
print(max(num))
print(sum(num))
num.append(5)
print (num)

3
5
3
12
37
[3, 5, 7, 10, 12, 5]


In [34]:
num=[3,5,7,8]
num.append(15)
print(num)


[3, 5, 7, 8, 15]


In [11]:
A=np.array([[11,22,33],
            [44,55,66],
            [77,88,99]])
print(A.T)

[[11 44 77]
 [22 55 88]
 [33 66 99]]


In [12]:
a=np.array([2,3,4])
b=np.array([3,6,9])
c=np.dot(a,b)
print(c)


60


In [13]:
a=np.array([1,3])
b=np.array([7,9])
a@b


np.int64(34)

In [14]:
a=np.array([1,5,6])
b=np.array([4,6,7])
r=np.matmul(a,b)
print(r)


76


In [16]:
A=np.array([[1,3,4,5],
            [2,3,4,5],
            [4,6,7,8]])
print(A.T)

[[1 2 4]
 [3 3 6]
 [4 4 7]
 [5 5 8]]
